-- Sample data so the listing page has content on first run.
-- The database is in-memory, so this is re-applied on every startup.
INSERT INTO person (first_name, last_name, email_address, street_address, city, state, zip_code) VALUES
    ('Ada', 'Lovelace', 'ada@example.com', '12 Analytical Engine Way', 'Boston', 'MA', '02110'),
    ('Grace', 'Hopper', 'grace@example.com', '707 Compiler Court', 'Arlington', 'VA', '22201'),
    ('Alan', 'Turing', 'alan@example.com', '54 Enigma Lane', 'Princeton', 'NJ', '08540'),
    ('Katherine', 'Johnson', 'katherine@example.com', '88 Orbital Drive', 'Hampton', 'VA', '23666'),
    ('Linus', 'Torvalds', 'linus@example.com', '101 Kernel Street', 'Portland', 'OR', '97201'),
    ('Margaret', 'Hamilton', 'margaret@example.com', '23 Apollo Avenue', 'Cambridge', 'MA', '02139'),
    ('Dennis', 'Ritchie', 'dennis@example.com', '5 Unix Boulevard', 'Murray Hill', 'NJ', '07974'),
    ('Barbara', 'Liskov', 'barbara@example.com', '42 Substitution Way', 'Cambridge', 'MA', '02142'),
    ('Tim', 'Berners-Lee', 'tim@example.com', '80 Hypertext Road', 'Boston', 'MA', '02115'),
    ('Donald', 'Knuth', 'donald@example.com', '314 Algorithm Place', 'Stanford', 'CA', '94305'),
    ('Hedy', 'Lamarr', 'hedy@example.com', '24 Frequency Lane', 'Los Angeles', 'CA', '90012'),
    ('Claude', 'Shannon', 'claude@example.com', '1 Information Way', 'Petoskey', 'MI', '49770'),
    ('John', 'McCarthy', 'john@example.com', '7 Lisp Lane', 'Palo Alto', 'CA', '94301'),
    ('Marvin', 'Minsky', 'marvin@example.com', '9 Perceptron Court', 'Cambridge', 'MA', '02138'),
    ('Edsger', 'Dijkstra', 'edsger@example.com', '0 Shortest Path', 'Austin', 'TX', '78701'),
    ('Vint', 'Cerf', 'vint@example.com', '443 Protocol Drive', 'Reston', 'VA', '20190'),
    ('Radia', 'Perlman', 'radia@example.com', '802 Spanning Tree Road', 'Seattle', 'WA', '98101'),
    ('Bjarne', 'Stroustrup', 'bjarne@example.com', '11 Template Terrace', 'College Station', 'TX', '77840'),
    ('Guido', 'van Rossum', 'guido@example.com', '3 Indentation Street', 'San Jose', 'CA', '95110'),
    ('James', 'Gosling', 'james@example.com', '7 Bytecode Avenue', 'Mountain View', 'CA', '94043'),
    ('Ken', 'Thompson', 'ken@example.com', '6 Pipe Place', 'Murray Hill', 'NJ', '07974'),
    ('Brian', 'Kernighan', 'brian@example.com', '1 Hello World Way', 'Princeton', 'NJ', '08544'),
    ('Anita', 'Borg', 'anita@example.com', '46 Systers Street', 'Palo Alto', 'CA', '94304'),
    ('Frances', 'Allen', 'frances@example.com', '99 Optimizer Lane', 'Yorktown', 'NY', '10598'),
    ('Shafi', 'Goldwasser', 'shafi@example.com', '13 Zero Knowledge Rd', 'Cambridge', 'MA', '02140'),
    ('Leslie', 'Lamport', 'leslie@example.com', '64 Clock Tower Court', 'Mountain View', 'CA', '94041'),
    ('Andrew', 'Tanenbaum', 'andrew@example.com', '32 Minix Mews', 'Amsterdam', 'NY', '12010'),
    ('Niklaus', 'Wirth', 'niklaus@example.com', '2 Pascal Plaza', 'Zurich', 'NY', '10001'),
    ('Adele', 'Goldberg', 'adele@example.com', '80 Smalltalk Square', 'Palo Alto', 'CA', '94306'),
    ('Alan', 'Kay', 'alankay@example.com', '5 Dynabook Drive', 'Los Angeles', 'CA', '90024'),
    ('Douglas', 'Engelbart', 'douglas@example.com', '17 Mouse Lane', 'Menlo Park', 'CA', '94025'),
    ('Steve', 'Wozniak', 'steve@example.com', '1 Garage Way', 'Cupertino', 'CA', '95014'),
    ('Jean', 'Bartik', 'jean@example.com', '1946 ENIAC Avenue', 'Philadelphia', 'PA', '19104'),
    ('Mary', 'Allen Wilkes', 'maryaw@example.com', '12 Linc Loop', 'Baltimore', 'MD', '21201'),
    ('Sophie', 'Wilson', 'sophie@example.com', '32 ARM Avenue', 'Cambridge', 'MA', '02141'),
    ('Carl', 'Sassenrath', 'carl@example.com', '7 Amiga Alley', 'Ukiah', 'CA', '95482'),
    ('Bill', 'Joy', 'bill@example.com', '4 Vi Editor Court', 'Aspen', 'CO', '81611'),
    ('Rasmus', 'Lerdorf', 'rasmus@example.com', '5 Hypertext Pre Way', 'Sunnyvale', 'CA', '94085'),
    ('Yukihiro', 'Matsumoto', 'yukihiro@example.com', '20 Ruby Road', 'Matsue', 'HI', '96701'),
    ('Brendan', 'Eich', 'brendan@example.com', '10 Prototype Place', 'Mountain View', 'CA', '94040'),
    ('John', 'Resig', 'johnresig@example.com', '1 Selector Street', 'Brooklyn', 'NY', '11201'),
    ('Grace', 'Murray', 'gracem@example.com', '60 Nanosecond Lane', 'New York', 'NY', '10007');
