-- Sample data so the listing page has content on first run.
-- The database is in-memory, so this is re-applied on every startup.
INSERT INTO person (first_name, last_name, email_address, street_address, city, state, zip_code) VALUES
    ('Ada', 'Lovelace', 'ada@example.com', '12 Analytical Engine Way', 'Boston', 'MA', '02110'),
    ('Grace', 'Hopper', 'grace@example.com', '707 Compiler Court', 'Arlington', 'VA', '22201'),
    ('Alan', 'Turing', 'alan@example.com', '54 Enigma Lane', 'Princeton', 'NJ', '08540'),
    ('Katherine', 'Johnson', 'katherine@example.com', '88 Orbital Drive', 'Hampton', 'VA', '23666'),
    ('Linus', 'Torvalds', 'linus@example.com', '101 Kernel Street', 'Portland', 'OR', '97201'),
    ('Margaret', 'Hamilton', 'margaret@example.com', '23 Apollo Avenue', 'Cambridge', 'MA', '02139'),
    ('Dennis', 'Ritchie', 'dennis@example.com', '5 Unix Boulevard', 'Murray Hill', 'NJ', '07974'),
    ('Barbara', 'Liskov', 'barbara@example.com', '42 Substitution Way', 'Cambridge', 'MA', '02142'),
    ('Tim', 'Berners-Lee', 'tim@example.com', '80 Hypertext Road', 'Boston', 'MA', '02115'),
    ('Donald', 'Knuth', 'donald@example.com', '314 Algorithm Place', 'Stanford', 'CA', '94305'),
    ('Hedy', 'Lamarr', 'hedy@example.com', '24 Frequency Lane', 'Los Angeles', 'CA', '90012'),
    ('Claude', 'Shannon', 'claude@example.com', '1 Information Way', 'Petoskey', 'MI', '49770'),
    ('John', 'McCarthy', 'john@example.com', '7 Lisp Lane', 'Palo Alto', 'CA', '94301'),
    ('Marvin', 'Minsky', 'marvin@example.com', '9 Perceptron Court', 'Cambridge', 'MA', '02138'),
    ('Edsger', 'Dijkstra', 'edsger@example.com', '0 Shortest Path', 'Austin', 'TX', '78701'),
    ('Vint', 'Cerf', 'vint@example.com', '443 Protocol Drive', 'Reston', 'VA', '20190'),
    ('Radia', 'Perlman', 'radia@example.com', '802 Spanning Tree Road', 'Seattle', 'WA', '98101'),
    ('Bjarne', 'Stroustrup', 'bjarne@example.com', '11 Template Terrace', 'College Station', 'TX', '77840'),
    ('Guido', 'van Rossum', 'guido@example.com', '3 Indentation Street', 'San Jose', 'CA', '95110'),
    ('James', 'Gosling', 'james@example.com', '7 Bytecode Avenue', 'Mountain View', 'CA', '94043'),
    ('Ken', 'Thompson', 'ken@example.com', '6 Pipe Place', 'Murray Hill', 'NJ', '07974'),
    ('Brian', 'Kernighan', 'brian@example.com', '1 Hello World Way', 'Princeton', 'NJ', '08544'),
    ('Anita', 'Borg', 'anita@example.com', '46 Systers Street', 'Palo Alto', 'CA', '94304'),
    ('Frances', 'Allen', 'frances@example.com', '99 Optimizer Lane', 'Yorktown', 'NY', '10598'),
    ('Shafi', 'Goldwasser', 'shafi@example.com', '13 Zero Knowledge Rd', 'Cambridge', 'MA', '02140'),
    ('Leslie', 'Lamport', 'leslie@example.com', '64 Clock Tower Court', 'Mountain View', 'CA', '94041'),
    ('Andrew', 'Tanenbaum', 'andrew@example.com', '32 Minix Mews', 'Amsterdam', 'NY', '12010'),
    ('Niklaus', 'Wirth', 'niklaus@example.com', '2 Pascal Plaza', 'Zurich', 'NY', '10001'),
    ('Adele', 'Goldberg', 'adele@example.com', '80 Smalltalk Square', 'Palo Alto', 'CA', '94306'),
    ('Alan', 'Kay', 'alankay@example.com', '5 Dynabook Drive', 'Los Angeles', 'CA', '90024'),
    ('Douglas', 'Engelbart', 'douglas@example.com', '17 Mouse Lane', 'Menlo Park', 'CA', '94025'),
    ('Steve', 'Wozniak', 'steve@example.com', '1 Garage Way', 'Cupertino', 'CA', '95014'),
    ('Jean', 'Bartik', 'jean@example.com', '1946 ENIAC Avenue', 'Philadelphia', 'PA', '19104'),
    ('Mary', 'Allen Wilkes', 'maryaw@example.com', '12 Linc Loop', 'Baltimore', 'MD', '21201'),
    ('Sophie', 'Wilson', 'sophie@example.com', '32 ARM Avenue', 'Cambridge', 'MA', '02141'),
    ('Carl', 'Sassenrath', 'carl@example.com', '7 Amiga Alley', 'Ukiah', 'CA', '95482'),
    ('Bill', 'Joy', 'bill@example.com', '4 Vi Editor Court', 'Aspen', 'CO', '81611'),
    ('Rasmus', 'Lerdorf', 'rasmus@example.com', '5 Hypertext Pre Way', 'Sunnyvale', 'CA', '94085'),
    ('Yukihiro', 'Matsumoto', 'yukihiro@example.com', '20 Ruby Road', 'Matsue', 'HI', '96701'),
    ('Brendan', 'Eich', 'brendan@example.com', '10 Prototype Place', 'Mountain View', 'CA', '94040'),
    ('John', 'Resig', 'johnresig@example.com', '1 Selector Street', 'Brooklyn', 'NY', '11201'),
    ('Grace', 'Murray', 'gracem@example.com', '60 Nanosecond Lane', 'New York', 'NY', '10007'),
    ('Oliver', 'Adams', 'oliver.adams@example.com', '14 Maple Street', 'Chicago', 'IL', '60601'),
    ('Emma', 'Baker', 'emma.baker@example.com', '28 Oak Avenue', 'Denver', 'CO', '80201'),
    ('Noah', 'Campbell', 'noah.campbell@example.com', '5 Pine Road', 'Phoenix', 'AZ', '85001'),
    ('Ava', 'Carter', 'ava.carter@example.com', '77 Elm Drive', 'Dallas', 'TX', '75201'),
    ('Liam', 'Clark', 'liam.clark@example.com', '33 Cedar Lane', 'Houston', 'TX', '77001'),
    ('Sophia', 'Collins', 'sophia.collins@example.com', '101 Birch Blvd', 'Atlanta', 'GA', '30301'),
    ('Mason', 'Davis', 'mason.davis@example.com', '9 Walnut Way', 'Miami', 'FL', '33101'),
    ('Isabella', 'Evans', 'isabella.evans@example.com', '200 Spruce Court', 'Seattle', 'WA', '98001'),
    ('Ethan', 'Foster', 'ethan.foster@example.com', '55 Willow Path', 'Portland', 'OR', '97001'),
    ('Mia', 'Garcia', 'mia.garcia@example.com', '8 Chestnut Circle', 'San Diego', 'CA', '92101'),
    ('Lucas', 'Green', 'lucas.green@example.com', '44 Poplar Place', 'San Antonio', 'TX', '78201'),
    ('Charlotte', 'Hall', 'charlotte.hall@example.com', '17 Ash Street', 'Nashville', 'TN', '37201'),
    ('Aiden', 'Harris', 'aiden.harris@example.com', '63 Redwood Road', 'Louisville', 'KY', '40201'),
    ('Amelia', 'Hill', 'amelia.hill@example.com', '3 Fir Lane', 'Baltimore', 'MD', '21202'),
    ('Jackson', 'Hughes', 'jackson.hughes@example.com', '720 Sycamore Ave', 'Indianapolis', 'IN', '46201'),
    ('Harper', 'Jackson', 'harper.jackson@example.com', '11 Magnolia Drive', 'Columbus', 'OH', '43201'),
    ('Sebastian', 'James', 'sebastian.j@example.com', '88 Dogwood Court', 'Charlotte', 'NC', '28201'),
    ('Evelyn', 'Johnson', 'evelyn.j@example.com', '22 Cypress Blvd', 'Memphis', 'TN', '38101'),
    ('Carter', 'Jones', 'carter.jones@example.com', '49 Hickory Way', 'El Paso', 'TX', '79901'),
    ('Abigail', 'King', 'abigail.king@example.com', '6 Holly Circle', 'Fort Worth', 'TX', '76101'),
    ('Owen', 'Lee', 'owen.lee@example.com', '35 Juniper Street', 'Sacramento', 'CA', '95801'),
    ('Emily', 'Lewis', 'emily.lewis@example.com', '190 Laurel Avenue', 'Boston', 'MA', '02201'),
    ('Wyatt', 'Lopez', 'wyatt.lopez@example.com', '15 Linden Lane', 'Kansas City', 'MO', '64101'),
    ('Aria', 'Martin', 'aria.martin@example.com', '71 Locust Road', 'Mesa', 'AZ', '85201'),
    ('Henry', 'Martinez', 'henry.martinez@example.com', '4 Mimosa Drive', 'Omaha', 'NE', '68101'),
    ('Ella', 'Miller', 'ella.miller@example.com', '58 Mulberry Blvd', 'Raleigh', 'NC', '27601'),
    ('Luke', 'Mitchell', 'luke.mitchell@example.com', '111 Myrtle Court', 'Colorado Spgs', 'CO', '80901'),
    ('Scarlett', 'Moore', 'scarlett.m@example.com', '27 Olive Way', 'Virginia Beach', 'VA', '23451'),
    ('Jack', 'Morgan', 'jack.morgan@example.com', '80 Orchid Path', 'Oakland', 'CA', '94601'),
    ('Victoria', 'Nelson', 'victoria.n@example.com', '39 Paloma Street', 'Minneapolis', 'MN', '55401'),
    ('James', 'Parker', 'james.parker@example.com', '12 Peach Avenue', 'Tulsa', 'OK', '74101'),
    ('Luna', 'Perez', 'luna.perez@example.com', '66 Plum Lane', 'Tampa', 'FL', '33601'),
    ('Logan', 'Phillips', 'logan.phillips@example.com', '7 Pecan Circle', 'Arlington', 'TX', '76001'),
    ('Grace', 'Reed', 'grace.reed@example.com', '93 Rosewood Road', 'New Orleans', 'LA', '70112'),
    ('Elijah', 'Rivera', 'elijah.rivera@example.com', '21 Sage Blvd', 'Bakersfield', 'CA', '93301'),
    ('Chloe', 'Roberts', 'chloe.roberts@example.com', '50 Sequoia Drive', 'Honolulu', 'HI', '96801'),
    ('Benjamin', 'Robinson', 'benjamin.r@example.com', '14 Sumac Court', 'Anaheim', 'CA', '92801'),
    ('Zoey', 'Rodriguez', 'zoey.rodriguez@example.com', '38 Sunflower Ave', 'Aurora', 'CO', '80010'),
    ('Alexander', 'Ross', 'alexander.r@example.com', '2 Sweetgum Way', 'Santa Ana', 'CA', '92701'),
    ('Penelope', 'Scott', 'penelope.s@example.com', '45 Tamarack Path', 'Corpus Christi', 'TX', '78401'),
    ('Daniel', 'Smith', 'daniel.smith@example.com', '67 Teak Street', 'Riverside', 'CA', '92501'),
    ('Riley', 'Stewart', 'riley.stewart@example.com', '19 Thistle Avenue', 'St Louis', 'MO', '63101'),
    ('Matthew', 'Taylor', 'matthew.t@example.com', '83 Tulip Lane', 'Pittsburgh', 'PA', '15201'),
    ('Layla', 'Thomas', 'layla.thomas@example.com', '30 Tupelo Circle', 'Anchorage', 'AK', '99501'),
    ('Elias', 'Thompson', 'elias.t@example.com', '54 Turpentine Blvd', 'Stockton', 'CA', '95201'),
    ('Lillian', 'Turner', 'lillian.t@example.com', '77 Verbena Drive', 'Cincinnati', 'OH', '45201'),
    ('David', 'Walker', 'david.walker@example.com', '16 Violet Road', 'Greensboro', 'NC', '27401'),
    ('Nora', 'Ward', 'nora.ward@example.com', '41 Walnut Court', 'Toledo', 'OH', '43601'),
    ('Ryan', 'Watson', 'ryan.watson@example.com', '25 Wisteria Way', 'Newark', 'NJ', '07101'),
    ('Hannah', 'White', 'hannah.white@example.com', '10 Yew Street', 'Buffalo', 'NY', '14201'),
    ('Nathan', 'Williams', 'nathan.w@example.com', '92 Zinnia Avenue', 'Plano', 'TX', '75024'),
    ('Leah', 'Wilson', 'leah.wilson@example.com', '37 Acacia Lane', 'Lincoln', 'NE', '68501'),
    ('Caleb', 'Wood', 'caleb.wood@example.com', '5 Alder Circle', 'Henderson', 'NV', '89002'),
    ('Addison', 'Wright', 'addison.w@example.com', '61 Almond Drive', 'Chandler', 'AZ', '85224'),
    ('Joshua', 'Young', 'joshua.young@example.com', '18 Aloe Road', 'Scottsdale', 'AZ', '85251'),
    ('Aubrey', 'Allen', 'aubrey.allen@example.com', '74 Amaranth Blvd', 'Madison', 'WI', '53701'),
    ('Samuel', 'Anderson', 'samuel.a@example.com', '29 Arborvitae Court', 'Reno', 'NV', '89501'),
    ('Stella', 'Bailey', 'stella.bailey@example.com', '48 Arrowwood Way', 'Baton Rouge', 'LA', '70801'),
    ('Joseph', 'Barnes', 'joseph.barnes@example.com', '6 Aspen Path', 'Richmond', 'VA', '23218'),
    ('Violet', 'Bell', 'violet.bell@example.com', '33 Aster Street', 'Spokane', 'WA', '99201'),
    ('Isaiah', 'Bennett', 'isaiah.b@example.com', '57 Azalea Avenue', 'Des Moines', 'IA', '50301'),
    ('Hazel', 'Brooks', 'hazel.brooks@example.com', '22 Balsa Lane', 'Lubbock', 'TX', '79401'),
    ('Andrew', 'Brown', 'andrew.brown@example.com', '86 Bamboo Circle', 'Garland', 'TX', '75040'),
    ('Aurora', 'Bryant', 'aurora.bryant@example.com', '11 Baywood Drive', 'Winston-Salem', 'NC', '27101'),
    ('Dylan', 'Butler', 'dylan.butler@example.com', '43 Bayberry Road', 'Hialeah', 'FL', '33010'),
    ('Savannah', 'Cameron', 'savannah.c@example.com', '70 Beech Blvd', 'Fremont', 'CA', '94536'),
    ('Gabriel', 'Campbell', 'gabriel.c@example.com', '36 Begonia Court', 'Norfolk', 'VA', '23501'),
    ('Claire', 'Carr', 'claire.carr@example.com', '8 Bergamot Way', 'Irvine', 'CA', '92602'),
    ('Anthony', 'Chapman', 'anthony.c@example.com', '52 Birchwood Path', 'Laredo', 'TX', '78040'),
    ('Paisley', 'Cole', 'paisley.cole@example.com', '19 Blackthorn Ave', 'Madison', 'WI', '53702'),
    ('Lincoln', 'Cooper', 'lincoln.c@example.com', '64 Bluebell Street', 'Durham', 'NC', '27701'),
    ('Elena', 'Cox', 'elena.cox@example.com', '31 Bluegrass Lane', 'Orlando', 'FL', '32801'),
    ('Hunter', 'Cruz', 'hunter.cruz@example.com', '75 Bottlebrush Cir', 'St Petersburg', 'FL', '33701'),
    ('Naomi', 'Dean', 'naomi.dean@example.com', '26 Boxwood Drive', 'Jersey City', 'NJ', '07302'),
    ('Julian', 'Diaz', 'julian.diaz@example.com', '44 Briar Road', 'Chula Vista', 'CA', '91910'),
    ('Lily', 'Dixon', 'lily.dixon@example.com', '13 Broom Blvd', 'El Monte', 'CA', '91731'),
    ('Eli', 'Edwards', 'eli.edwards@example.com', '89 Buckeye Court', 'Lakewood', 'CO', '80226'),
    ('Natalie', 'Ellis', 'natalie.ellis@example.com', '47 Buttonwood Way', 'Sunnyvale', 'CA', '94086'),
    ('Aaron', 'Ferguson', 'aaron.f@example.com', '20 Camellia Path', 'Moreno Valley', 'CA', '92551'),
    ('Samantha', 'Fisher', 'samantha.f@example.com', '58 Camphor Street', 'Oxnard', 'CA', '93030'),
    ('Charles', 'Fleming', 'charles.f@example.com', '3 Canary Avenue', 'Fayetteville', 'NC', '28301'),
    ('Kaylee', 'Ford', 'kaylee.ford@example.com', '71 Candytuft Lane', 'Aurora', 'IL', '60505'),
    ('Christopher', 'Fox', 'christopher.f@example.com', '35 Carob Circle', 'Ontario', 'CA', '91761'),
    ('Alice', 'Freeman', 'alice.freeman@example.com', '16 Cassia Drive', 'Fontana', 'CA', '92335'),
    ('Dominic', 'Gibson', 'dominic.g@example.com', '90 Catalpa Road', 'Rancho Cucamonga', 'CA', '91730'),
    ('Zoe', 'Graham', 'zoe.graham@example.com', '27 Cedar Bluff Ave', 'Tallahassee', 'FL', '32301'),
    ('Jonathan', 'Grant', 'jonathan.g@example.com', '62 Cereus Court', 'Montgomery', 'AL', '36101'),
    ('Peyton', 'Gray', 'peyton.gray@example.com', '9 Cherry Lane', 'Huntsville', 'AL', '35801'),
    ('Audrey', 'Griffin', 'audrey.g@example.com', '53 Chokecherry Way', 'Akron', 'OH', '44301'),
    ('Nicholas', 'Hamilton', 'nicholas.h@example.com', '38 Chrysanthemum Pl', 'Shreveport', 'LA', '71101'),
    ('Brooklyn', 'Hansen', 'brooklyn.h@example.com', '14 Cinnamon Drive', 'Augusta', 'GA', '30901'),
    ('Christian', 'Harper', 'christian.h@example.com', '76 Citrus Road', 'Grand Rapids', 'MI', '49501'),
    ('Willow', 'Hart', 'willow.hart@example.com', '42 Clover Blvd', 'Salt Lake City', 'UT', '84101'),
    ('Jeremiah', 'Hayes', 'jeremiah.h@example.com', '23 Cockscomb Court', 'Huntington Beach', 'CA', '92647'),
    ('Mackenzie', 'Henderson', 'mackenzie.h@example.com', '68 Columbine Way', 'Worcester', 'MA', '01601'),
    ('Josiah', 'Henry', 'josiah.henry@example.com', '5 Coneflower Path', 'Knoxville', 'TN', '37901'),
    ('Genesis', 'Hill', 'genesis.hill@example.com', '31 Coral Street', 'Providence', 'RI', '02901'),
    ('Xavier', 'Holmes', 'xavier.h@example.com', '57 Cornflower Lane', 'Glendale', 'AZ', '85301'),
    ('Serenity', 'Howard', 'serenity.h@example.com', '18 Cosmos Avenue', 'Tacoma', 'WA', '98401'),
    ('Miles', 'Hudson', 'miles.hudson@example.com', '44 Dahlia Drive', 'Boise', 'ID', '83701');
