-- Sample data so the listing page has content on first run.
-- The database is in-memory, so this is re-applied on every startup.
INSERT INTO person (first_name, last_name, email_address, street_address, city, state, zip_code) VALUES
    ('Ada', 'Lovelace', 'ada@example.com', '12 Analytical Engine Way', 'Boston', 'MA', '02110'),
    ('Grace', 'Hopper', 'grace@example.com', '707 Compiler Court', 'Arlington', 'VA', '22201'),
    ('Alan', 'Turing', 'alan@example.com', '54 Enigma Lane', 'Princeton', 'NJ', '08540'),
    ('Katherine', 'Johnson', 'katherine@example.com', '88 Orbital Drive', 'Hampton', 'VA', '23666'),
    ('Linus', 'Torvalds', 'linus@example.com', '101 Kernel Street', 'Portland', 'OR', '97201'),
    ('Margaret', 'Hamilton', 'margaret@example.com', '23 Apollo Avenue', 'Cambridge', 'MA', '02139'),
    ('Dennis', 'Ritchie', 'dennis@example.com', '5 Unix Boulevard', 'Murray Hill', 'NJ', '07974'),
    ('Barbara', 'Liskov', 'barbara@example.com', '42 Substitution Way', 'Cambridge', 'MA', '02142'),
    ('Tim', 'Berners-Lee', 'tim@example.com', '80 Hypertext Road', 'Boston', 'MA', '02115'),
    ('Donald', 'Knuth', 'donald@example.com', '314 Algorithm Place', 'Stanford', 'CA', '94305'),
    ('Hedy', 'Lamarr', 'hedy@example.com', '24 Frequency Lane', 'Los Angeles', 'CA', '90012'),
    ('Claude', 'Shannon', 'claude@example.com', '1 Information Way', 'Petoskey', 'MI', '49770'),
    ('John', 'McCarthy', 'john@example.com', '7 Lisp Lane', 'Palo Alto', 'CA', '94301'),
    ('Marvin', 'Minsky', 'marvin@example.com', '9 Perceptron Court', 'Cambridge', 'MA', '02138'),
    ('Edsger', 'Dijkstra', 'edsger@example.com', '0 Shortest Path', 'Austin', 'TX', '78701'),
    ('Vint', 'Cerf', 'vint@example.com', '443 Protocol Drive', 'Reston', 'VA', '20190'),
    ('Radia', 'Perlman', 'radia@example.com', '802 Spanning Tree Road', 'Seattle', 'WA', '98101'),
    ('Bjarne', 'Stroustrup', 'bjarne@example.com', '11 Template Terrace', 'College Station', 'TX', '77840'),
    ('Guido', 'van Rossum', 'guido@example.com', '3 Indentation Street', 'San Jose', 'CA', '95110'),
    ('James', 'Gosling', 'james@example.com', '7 Bytecode Avenue', 'Mountain View', 'CA', '94043'),
    ('Ken', 'Thompson', 'ken@example.com', '6 Pipe Place', 'Murray Hill', 'NJ', '07974'),
    ('Brian', 'Kernighan', 'brian@example.com', '1 Hello World Way', 'Princeton', 'NJ', '08544'),
    ('Anita', 'Borg', 'anita@example.com', '46 Systers Street', 'Palo Alto', 'CA', '94304'),
    ('Frances', 'Allen', 'frances@example.com', '99 Optimizer Lane', 'Yorktown', 'NY', '10598'),
    ('Shafi', 'Goldwasser', 'shafi@example.com', '13 Zero Knowledge Rd', 'Cambridge', 'MA', '02140'),
    ('Leslie', 'Lamport', 'leslie@example.com', '64 Clock Tower Court', 'Mountain View', 'CA', '94041'),
    ('Andrew', 'Tanenbaum', 'andrew@example.com', '32 Minix Mews', 'Amsterdam', 'NY', '12010'),
    ('Niklaus', 'Wirth', 'niklaus@example.com', '2 Pascal Plaza', 'Zurich', 'NY', '10001'),
    ('Adele', 'Goldberg', 'adele@example.com', '80 Smalltalk Square', 'Palo Alto', 'CA', '94306'),
    ('Alan', 'Kay', 'alankay@example.com', '5 Dynabook Drive', 'Los Angeles', 'CA', '90024'),
    ('Douglas', 'Engelbart', 'douglas@example.com', '17 Mouse Lane', 'Menlo Park', 'CA', '94025'),
    ('Steve', 'Wozniak', 'steve@example.com', '1 Garage Way', 'Cupertino', 'CA', '95014'),
    ('Jean', 'Bartik', 'jean@example.com', '1946 ENIAC Avenue', 'Philadelphia', 'PA', '19104'),
    ('Mary', 'Allen Wilkes', 'maryaw@example.com', '12 Linc Loop', 'Baltimore', 'MD', '21201'),
    ('Sophie', 'Wilson', 'sophie@example.com', '32 ARM Avenue', 'Cambridge', 'MA', '02141'),
    ('Carl', 'Sassenrath', 'carl@example.com', '7 Amiga Alley', 'Ukiah', 'CA', '95482'),
    ('Bill', 'Joy', 'bill@example.com', '4 Vi Editor Court', 'Aspen', 'CO', '81611'),
    ('Rasmus', 'Lerdorf', 'rasmus@example.com', '5 Hypertext Pre Way', 'Sunnyvale', 'CA', '94085'),
    ('Yukihiro', 'Matsumoto', 'yukihiro@example.com', '20 Ruby Road', 'Matsue', 'HI', '96701'),
    ('Brendan', 'Eich', 'brendan@example.com', '10 Prototype Place', 'Mountain View', 'CA', '94040'),
    ('John', 'Resig', 'johnresig@example.com', '1 Selector Street', 'Brooklyn', 'NY', '11201'),
    ('Grace', 'Murray', 'gracem@example.com', '60 Nanosecond Lane', 'New York', 'NY', '10007'),
    ('Oliver', 'Adams', 'oliver.adams@example.com', '14 Maple Street', 'Chicago', 'IL', '60601'),
    ('Emma', 'Baker', 'emma.baker@example.com', '28 Oak Avenue', 'Denver', 'CO', '80201'),
    ('Noah', 'Campbell', 'noah.campbell@example.com', '5 Pine Road', 'Phoenix', 'AZ', '85001'),
    ('Ava', 'Carter', 'ava.carter@example.com', '77 Elm Drive', 'Dallas', 'TX', '75201'),
    ('Liam', 'Clark', 'liam.clark@example.com', '33 Cedar Lane', 'Houston', 'TX', '77001'),
    ('Sophia', 'Collins', 'sophia.collins@example.com', '101 Birch Blvd', 'Atlanta', 'GA', '30301'),
    ('Mason', 'Davis', 'mason.davis@example.com', '9 Walnut Way', 'Miami', 'FL', '33101'),
    ('Isabella', 'Evans', 'isabella.evans@example.com', '200 Spruce Court', 'Seattle', 'WA', '98001'),
    ('Ethan', 'Foster', 'ethan.foster@example.com', '55 Willow Path', 'Portland', 'OR', '97001'),
    ('Mia', 'Garcia', 'mia.garcia@example.com', '8 Chestnut Circle', 'San Diego', 'CA', '92101'),
    ('Lucas', 'Green', 'lucas.green@example.com', '44 Poplar Place', 'San Antonio', 'TX', '78201'),
    ('Charlotte', 'Hall', 'charlotte.hall@example.com', '17 Ash Street', 'Nashville', 'TN', '37201'),
    ('Aiden', 'Harris', 'aiden.harris@example.com', '63 Redwood Road', 'Louisville', 'KY', '40201'),
    ('Amelia', 'Hill', 'amelia.hill@example.com', '3 Fir Lane', 'Baltimore', 'MD', '21202'),
    ('Jackson', 'Hughes', 'jackson.hughes@example.com', '720 Sycamore Ave', 'Indianapolis', 'IN', '46201'),
    ('Harper', 'Jackson', 'harper.jackson@example.com', '11 Magnolia Drive', 'Columbus', 'OH', '43201'),
    ('Sebastian', 'James', 'sebastian.j@example.com', '88 Dogwood Court', 'Charlotte', 'NC', '28201'),
    ('Evelyn', 'Johnson', 'evelyn.j@example.com', '22 Cypress Blvd', 'Memphis', 'TN', '38101'),
    ('Carter', 'Jones', 'carter.jones@example.com', '49 Hickory Way', 'El Paso', 'TX', '79901'),
    ('Abigail', 'King', 'abigail.king@example.com', '6 Holly Circle', 'Fort Worth', 'TX', '76101'),
    ('Owen', 'Lee', 'owen.lee@example.com', '35 Juniper Street', 'Sacramento', 'CA', '95801'),
    ('Emily', 'Lewis', 'emily.lewis@example.com', '190 Laurel Avenue', 'Boston', 'MA', '02201'),
    ('Wyatt', 'Lopez', 'wyatt.lopez@example.com', '15 Linden Lane', 'Kansas City', 'MO', '64101'),
    ('Aria', 'Martin', 'aria.martin@example.com', '71 Locust Road', 'Mesa', 'AZ', '85201'),
    ('Henry', 'Martinez', 'henry.martinez@example.com', '4 Mimosa Drive', 'Omaha', 'NE', '68101'),
    ('Ella', 'Miller', 'ella.miller@example.com', '58 Mulberry Blvd', 'Raleigh', 'NC', '27601'),
    ('Luke', 'Mitchell', 'luke.mitchell@example.com', '111 Myrtle Court', 'Colorado Spgs', 'CO', '80901'),
    ('Scarlett', 'Moore', 'scarlett.m@example.com', '27 Olive Way', 'Virginia Beach', 'VA', '23451'),
    ('Jack', 'Morgan', 'jack.morgan@example.com', '80 Orchid Path', 'Oakland', 'CA', '94601'),
    ('Victoria', 'Nelson', 'victoria.n@example.com', '39 Paloma Street', 'Minneapolis', 'MN', '55401'),
    ('James', 'Parker', 'james.parker@example.com', '12 Peach Avenue', 'Tulsa', 'OK', '74101'),
    ('Luna', 'Perez', 'luna.perez@example.com', '66 Plum Lane', 'Tampa', 'FL', '33601'),
    ('Logan', 'Phillips', 'logan.phillips@example.com', '7 Pecan Circle', 'Arlington', 'TX', '76001'),
    ('Grace', 'Reed', 'grace.reed@example.com', '93 Rosewood Road', 'New Orleans', 'LA', '70112'),
    ('Elijah', 'Rivera', 'elijah.rivera@example.com', '21 Sage Blvd', 'Bakersfield', 'CA', '93301'),
    ('Chloe', 'Roberts', 'chloe.roberts@example.com', '50 Sequoia Drive', 'Honolulu', 'HI', '96801'),
    ('Benjamin', 'Robinson', 'benjamin.r@example.com', '14 Sumac Court', 'Anaheim', 'CA', '92801'),
    ('Zoey', 'Rodriguez', 'zoey.rodriguez@example.com', '38 Sunflower Ave', 'Aurora', 'CO', '80010'),
    ('Alexander', 'Ross', 'alexander.r@example.com', '2 Sweetgum Way', 'Santa Ana', 'CA', '92701'),
    ('Penelope', 'Scott', 'penelope.s@example.com', '45 Tamarack Path', 'Corpus Christi', 'TX', '78401'),
    ('Daniel', 'Smith', 'daniel.smith@example.com', '67 Teak Street', 'Riverside', 'CA', '92501'),
    ('Riley', 'Stewart', 'riley.stewart@example.com', '19 Thistle Avenue', 'St Louis', 'MO', '63101'),
    ('Matthew', 'Taylor', 'matthew.t@example.com', '83 Tulip Lane', 'Pittsburgh', 'PA', '15201'),
    ('Layla', 'Thomas', 'layla.thomas@example.com', '30 Tupelo Circle', 'Anchorage', 'AK', '99501'),
    ('Elias', 'Thompson', 'elias.t@example.com', '54 Turpentine Blvd', 'Stockton', 'CA', '95201'),
    ('Lillian', 'Turner', 'lillian.t@example.com', '77 Verbena Drive', 'Cincinnati', 'OH', '45201'),
    ('David', 'Walker', 'david.walker@example.com', '16 Violet Road', 'Greensboro', 'NC', '27401'),
    ('Nora', 'Ward', 'nora.ward@example.com', '41 Walnut Court', 'Toledo', 'OH', '43601'),
    ('Ryan', 'Watson', 'ryan.watson@example.com', '25 Wisteria Way', 'Newark', 'NJ', '07101'),
    ('Hannah', 'White', 'hannah.white@example.com', '10 Yew Street', 'Buffalo', 'NY', '14201'),
    ('Nathan', 'Williams', 'nathan.w@example.com', '92 Zinnia Avenue', 'Plano', 'TX', '75024'),
    ('Leah', 'Wilson', 'leah.wilson@example.com', '37 Acacia Lane', 'Lincoln', 'NE', '68501'),
    ('Caleb', 'Wood', 'caleb.wood@example.com', '5 Alder Circle', 'Henderson', 'NV', '89002'),
    ('Addison', 'Wright', 'addison.w@example.com', '61 Almond Drive', 'Chandler', 'AZ', '85224'),
    ('Joshua', 'Young', 'joshua.young@example.com', '18 Aloe Road', 'Scottsdale', 'AZ', '85251'),
    ('Aubrey', 'Allen', 'aubrey.allen@example.com', '74 Amaranth Blvd', 'Madison', 'WI', '53701'),
    ('Samuel', 'Anderson', 'samuel.a@example.com', '29 Arborvitae Court', 'Reno', 'NV', '89501'),
    ('Stella', 'Bailey', 'stella.bailey@example.com', '48 Arrowwood Way', 'Baton Rouge', 'LA', '70801'),
    ('Joseph', 'Barnes', 'joseph.barnes@example.com', '6 Aspen Path', 'Richmond', 'VA', '23218'),
    ('Violet', 'Bell', 'violet.bell@example.com', '33 Aster Street', 'Spokane', 'WA', '99201'),
    ('Isaiah', 'Bennett', 'isaiah.b@example.com', '57 Azalea Avenue', 'Des Moines', 'IA', '50301'),
    ('Hazel', 'Brooks', 'hazel.brooks@example.com', '22 Balsa Lane', 'Lubbock', 'TX', '79401'),
    ('Andrew', 'Brown', 'andrew.brown@example.com', '86 Bamboo Circle', 'Garland', 'TX', '75040'),
    ('Aurora', 'Bryant', 'aurora.bryant@example.com', '11 Baywood Drive', 'Winston-Salem', 'NC', '27101'),
    ('Dylan', 'Butler', 'dylan.butler@example.com', '43 Bayberry Road', 'Hialeah', 'FL', '33010'),
    ('Savannah', 'Cameron', 'savannah.c@example.com', '70 Beech Blvd', 'Fremont', 'CA', '94536'),
    ('Gabriel', 'Campbell', 'gabriel.c@example.com', '36 Begonia Court', 'Norfolk', 'VA', '23501'),
    ('Claire', 'Carr', 'claire.carr@example.com', '8 Bergamot Way', 'Irvine', 'CA', '92602'),
    ('Anthony', 'Chapman', 'anthony.c@example.com', '52 Birchwood Path', 'Laredo', 'TX', '78040'),
    ('Paisley', 'Cole', 'paisley.cole@example.com', '19 Blackthorn Ave', 'Madison', 'WI', '53702'),
    ('Lincoln', 'Cooper', 'lincoln.c@example.com', '64 Bluebell Street', 'Durham', 'NC', '27701'),
    ('Elena', 'Cox', 'elena.cox@example.com', '31 Bluegrass Lane', 'Orlando', 'FL', '32801'),
    ('Hunter', 'Cruz', 'hunter.cruz@example.com', '75 Bottlebrush Cir', 'St Petersburg', 'FL', '33701'),
    ('Naomi', 'Dean', 'naomi.dean@example.com', '26 Boxwood Drive', 'Jersey City', 'NJ', '07302'),
    ('Julian', 'Diaz', 'julian.diaz@example.com', '44 Briar Road', 'Chula Vista', 'CA', '91910'),
    ('Lily', 'Dixon', 'lily.dixon@example.com', '13 Broom Blvd', 'El Monte', 'CA', '91731'),
    ('Eli', 'Edwards', 'eli.edwards@example.com', '89 Buckeye Court', 'Lakewood', 'CO', '80226'),
    ('Natalie', 'Ellis', 'natalie.ellis@example.com', '47 Buttonwood Way', 'Sunnyvale', 'CA', '94086'),
    ('Aaron', 'Ferguson', 'aaron.f@example.com', '20 Camellia Path', 'Moreno Valley', 'CA', '92551'),
    ('Samantha', 'Fisher', 'samantha.f@example.com', '58 Camphor Street', 'Oxnard', 'CA', '93030'),
    ('Charles', 'Fleming', 'charles.f@example.com', '3 Canary Avenue', 'Fayetteville', 'NC', '28301'),
    ('Kaylee', 'Ford', 'kaylee.ford@example.com', '71 Candytuft Lane', 'Aurora', 'IL', '60505'),
    ('Christopher', 'Fox', 'christopher.f@example.com', '35 Carob Circle', 'Ontario', 'CA', '91761'),
    ('Alice', 'Freeman', 'alice.freeman@example.com', '16 Cassia Drive', 'Fontana', 'CA', '92335'),
    ('Dominic', 'Gibson', 'dominic.g@example.com', '90 Catalpa Road', 'Rancho Cucamonga', 'CA', '91730'),
    ('Zoe', 'Graham', 'zoe.graham@example.com', '27 Cedar Bluff Ave', 'Tallahassee', 'FL', '32301'),
    ('Jonathan', 'Grant', 'jonathan.g@example.com', '62 Cereus Court', 'Montgomery', 'AL', '36101'),
    ('Peyton', 'Gray', 'peyton.gray@example.com', '9 Cherry Lane', 'Huntsville', 'AL', '35801'),
    ('Audrey', 'Griffin', 'audrey.g@example.com', '53 Chokecherry Way', 'Akron', 'OH', '44301'),
    ('Nicholas', 'Hamilton', 'nicholas.h@example.com', '38 Chrysanthemum Pl', 'Shreveport', 'LA', '71101'),
    ('Brooklyn', 'Hansen', 'brooklyn.h@example.com', '14 Cinnamon Drive', 'Augusta', 'GA', '30901'),
    ('Christian', 'Harper', 'christian.h@example.com', '76 Citrus Road', 'Grand Rapids', 'MI', '49501'),
    ('Willow', 'Hart', 'willow.hart@example.com', '42 Clover Blvd', 'Salt Lake City', 'UT', '84101'),
    ('Jeremiah', 'Hayes', 'jeremiah.h@example.com', '23 Cockscomb Court', 'Huntington Beach', 'CA', '92647'),
    ('Mackenzie', 'Henderson', 'mackenzie.h@example.com', '68 Columbine Way', 'Worcester', 'MA', '01601'),
    ('Josiah', 'Henry', 'josiah.henry@example.com', '5 Coneflower Path', 'Knoxville', 'TN', '37901'),
    ('Genesis', 'Hill', 'genesis.hill@example.com', '31 Coral Street', 'Providence', 'RI', '02901'),
    ('Xavier', 'Holmes', 'xavier.h@example.com', '57 Cornflower Lane', 'Glendale', 'AZ', '85301'),
    ('Serenity', 'Howard', 'serenity.h@example.com', '18 Cosmos Avenue', 'Tacoma', 'WA', '98401'),
    ('Miles', 'Hudson', 'miles.hudson@example.com', '44 Dahlia Drive', 'Boise', 'ID', '83701');

-- Notes for roughly 75%% of the people above (1-5 notes each, 1-5
-- sentences per note). Person ids are the 1-based insertion order of the
-- person rows. Generated deterministically; people whose id is a multiple
-- of 4 have no notes.
INSERT INTO note (person_id, note_text, created_at) VALUES
    (1, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -50, CURRENT_TIMESTAMP)),
    (1, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -87, CURRENT_TIMESTAMP)),
    (1, 'Usually unavailable on Friday afternoons.', DATEADD('DAY', -124, CURRENT_TIMESTAMP)),
    (2, 'Schedule quarterly check-ins going forward.', DATEADD('DAY', -63, CURRENT_TIMESTAMP)),
    (2, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -100, CURRENT_TIMESTAMP)),
    (2, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -137, CURRENT_TIMESTAMP)),
    (2, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -174, CURRENT_TIMESTAMP)),
    (2, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -211, CURRENT_TIMESTAMP)),
    (3, 'Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -76, CURRENT_TIMESTAMP)),
    (3, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -113, CURRENT_TIMESTAMP)),
    (5, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -102, CURRENT_TIMESTAMP)),
    (6, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -115, CURRENT_TIMESTAMP)),
    (6, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -152, CURRENT_TIMESTAMP)),
    (6, 'Has two accounts that should eventually be merged.', DATEADD('DAY', -189, CURRENT_TIMESTAMP)),
    (7, 'Requested a copy of the latest product brochure.', DATEADD('DAY', -128, CURRENT_TIMESTAMP)),
    (7, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -165, CURRENT_TIMESTAMP)),
    (7, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -202, CURRENT_TIMESTAMP)),
    (7, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -239, CURRENT_TIMESTAMP)),
    (7, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -276, CURRENT_TIMESTAMP)),
    (9, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -154, CURRENT_TIMESTAMP)),
    (9, 'Recently moved and updated their mailing address.', DATEADD('DAY', -191, CURRENT_TIMESTAMP)),
    (9, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -228, CURRENT_TIMESTAMP)),
    (9, 'Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -265, CURRENT_TIMESTAMP)),
    (10, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -167, CURRENT_TIMESTAMP)),
    (11, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -180, CURRENT_TIMESTAMP)),
    (11, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -217, CURRENT_TIMESTAMP)),
    (11, 'Interested in the premium support plan.', DATEADD('DAY', -254, CURRENT_TIMESTAMP)),
    (13, 'Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -206, CURRENT_TIMESTAMP)),
    (13, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -243, CURRENT_TIMESTAMP)),
    (14, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -219, CURRENT_TIMESTAMP)),
    (14, 'Very responsive and easy to work with.', DATEADD('DAY', -256, CURRENT_TIMESTAMP)),
    (14, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -293, CURRENT_TIMESTAMP)),
    (14, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -330, CURRENT_TIMESTAMP)),
    (15, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -232, CURRENT_TIMESTAMP)),
    (17, 'Asked for a follow-up call next quarter.', DATEADD('DAY', -258, CURRENT_TIMESTAMP)),
    (17, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -295, CURRENT_TIMESTAMP)),
    (17, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -332, CURRENT_TIMESTAMP)),
    (17, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -4, CURRENT_TIMESTAMP)),
    (17, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -41, CURRENT_TIMESTAMP)),
    (18, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -271, CURRENT_TIMESTAMP)),
    (18, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -308, CURRENT_TIMESTAMP)),
    (19, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -284, CURRENT_TIMESTAMP)),
    (19, 'Met at the annual industry conference in March.', DATEADD('DAY', -321, CURRENT_TIMESTAMP)),
    (19, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -358, CURRENT_TIMESTAMP)),
    (19, 'Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -30, CURRENT_TIMESTAMP)),
    (21, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -310, CURRENT_TIMESTAMP)),
    (21, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -347, CURRENT_TIMESTAMP)),
    (21, 'Prefers to be contacted by email.', DATEADD('DAY', -19, CURRENT_TIMESTAMP)),
    (22, 'Considering an upgrade once the current contract expires.', DATEADD('DAY', -323, CURRENT_TIMESTAMP)),
    (22, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -360, CURRENT_TIMESTAMP)),
    (22, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -32, CURRENT_TIMESTAMP)),
    (22, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -69, CURRENT_TIMESTAMP)),
    (22, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -106, CURRENT_TIMESTAMP)),
    (23, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -336, CURRENT_TIMESTAMP)),
    (23, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -8, CURRENT_TIMESTAMP)),
    (25, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -362, CURRENT_TIMESTAMP)),
    (26, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -10, CURRENT_TIMESTAMP)),
    (26, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -47, CURRENT_TIMESTAMP)),
    (26, 'Referred by a colleague from the Springfield office.', DATEADD('DAY', -84, CURRENT_TIMESTAMP)),
    (27, 'Provided detailed feedback on the new portal.', DATEADD('DAY', -23, CURRENT_TIMESTAMP)),
    (27, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -60, CURRENT_TIMESTAMP)),
    (27, 'Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -97, CURRENT_TIMESTAMP)),
    (27, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -134, CURRENT_TIMESTAMP)),
    (27, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -171, CURRENT_TIMESTAMP)),
    (29, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -49, CURRENT_TIMESTAMP)),
    (29, 'Has two accounts that should eventually be merged.', DATEADD('DAY', -86, CURRENT_TIMESTAMP)),
    (29, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -123, CURRENT_TIMESTAMP)),
    (29, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -160, CURRENT_TIMESTAMP)),
    (30, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -62, CURRENT_TIMESTAMP)),
    (31, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -75, CURRENT_TIMESTAMP)),
    (31, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -112, CURRENT_TIMESTAMP)),
    (31, 'Wants to be notified about regional events.', DATEADD('DAY', -149, CURRENT_TIMESTAMP)),
    (33, 'Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -101, CURRENT_TIMESTAMP)),
    (33, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -138, CURRENT_TIMESTAMP)),
    (34, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -114, CURRENT_TIMESTAMP)),
    (34, 'Interested in the premium support plan.', DATEADD('DAY', -151, CURRENT_TIMESTAMP)),
    (34, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -188, CURRENT_TIMESTAMP)),
    (34, 'Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -225, CURRENT_TIMESTAMP)),
    (35, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -127, CURRENT_TIMESTAMP)),
    (37, 'Very responsive and easy to work with.', DATEADD('DAY', -153, CURRENT_TIMESTAMP)),
    (37, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -190, CURRENT_TIMESTAMP)),
    (37, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -227, CURRENT_TIMESTAMP)),
    (37, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -264, CURRENT_TIMESTAMP)),
    (37, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -301, CURRENT_TIMESTAMP)),
    (38, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -166, CURRENT_TIMESTAMP)),
    (38, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -203, CURRENT_TIMESTAMP)),
    (39, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -179, CURRENT_TIMESTAMP)),
    (39, 'Left a voicemail regarding the open invoice.', DATEADD('DAY', -216, CURRENT_TIMESTAMP)),
    (39, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -253, CURRENT_TIMESTAMP)),
    (39, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -290, CURRENT_TIMESTAMP)),
    (41, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -205, CURRENT_TIMESTAMP)),
    (41, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -242, CURRENT_TIMESTAMP)),
    (41, 'Spoke with them about renewal pricing.', DATEADD('DAY', -279, CURRENT_TIMESTAMP)),
    (42, 'Met at the annual industry conference in March.', DATEADD('DAY', -218, CURRENT_TIMESTAMP)),
    (42, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -255, CURRENT_TIMESTAMP)),
    (42, 'Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -292, CURRENT_TIMESTAMP)),
    (42, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -329, CURRENT_TIMESTAMP)),
    (42, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -1, CURRENT_TIMESTAMP)),
    (43, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -231, CURRENT_TIMESTAMP)),
    (43, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -268, CURRENT_TIMESTAMP)),
    (45, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -257, CURRENT_TIMESTAMP)),
    (46, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -270, CURRENT_TIMESTAMP)),
    (46, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -307, CURRENT_TIMESTAMP)),
    (46, 'Schedule quarterly check-ins going forward.', DATEADD('DAY', -344, CURRENT_TIMESTAMP)),
    (47, 'Usually unavailable on Friday afternoons.', DATEADD('DAY', -283, CURRENT_TIMESTAMP)),
    (47, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -320, CURRENT_TIMESTAMP)),
    (47, 'Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -357, CURRENT_TIMESTAMP)),
    (47, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -29, CURRENT_TIMESTAMP)),
    (47, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -66, CURRENT_TIMESTAMP)),
    (49, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -309, CURRENT_TIMESTAMP)),
    (49, 'Referred by a colleague from the Springfield office.', DATEADD('DAY', -346, CURRENT_TIMESTAMP)),
    (49, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -18, CURRENT_TIMESTAMP)),
    (49, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -55, CURRENT_TIMESTAMP)),
    (50, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -322, CURRENT_TIMESTAMP)),
    (51, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -335, CURRENT_TIMESTAMP)),
    (51, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -7, CURRENT_TIMESTAMP)),
    (51, 'Requested a copy of the latest product brochure.', DATEADD('DAY', -44, CURRENT_TIMESTAMP)),
    (53, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -361, CURRENT_TIMESTAMP)),
    (53, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -33, CURRENT_TIMESTAMP)),
    (54, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -9, CURRENT_TIMESTAMP)),
    (54, 'Wants to be notified about regional events.', DATEADD('DAY', -46, CURRENT_TIMESTAMP)),
    (54, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -83, CURRENT_TIMESTAMP)),
    (54, 'Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -120, CURRENT_TIMESTAMP)),
    (55, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -22, CURRENT_TIMESTAMP)),
    (57, 'Interested in the premium support plan.', DATEADD('DAY', -48, CURRENT_TIMESTAMP)),
    (57, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -85, CURRENT_TIMESTAMP)),
    (57, 'Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -122, CURRENT_TIMESTAMP)),
    (57, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -159, CURRENT_TIMESTAMP)),
    (57, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -196, CURRENT_TIMESTAMP)),
    (58, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -61, CURRENT_TIMESTAMP)),
    (58, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -98, CURRENT_TIMESTAMP)),
    (59, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -74, CURRENT_TIMESTAMP)),
    (59, 'Longtime customer with an excellent payment history.', DATEADD('DAY', -111, CURRENT_TIMESTAMP)),
    (59, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -148, CURRENT_TIMESTAMP)),
    (59, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -185, CURRENT_TIMESTAMP)),
    (61, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -100, CURRENT_TIMESTAMP)),
    (61, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -137, CURRENT_TIMESTAMP)),
    (61, 'Asked for a follow-up call next quarter.', DATEADD('DAY', -174, CURRENT_TIMESTAMP)),
    (62, 'Left a voicemail regarding the open invoice.', DATEADD('DAY', -113, CURRENT_TIMESTAMP)),
    (62, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -150, CURRENT_TIMESTAMP)),
    (62, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -187, CURRENT_TIMESTAMP)),
    (62, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -224, CURRENT_TIMESTAMP)),
    (62, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -261, CURRENT_TIMESTAMP)),
    (63, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -126, CURRENT_TIMESTAMP)),
    (63, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -163, CURRENT_TIMESTAMP)),
    (65, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -152, CURRENT_TIMESTAMP)),
    (66, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -165, CURRENT_TIMESTAMP)),
    (66, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -202, CURRENT_TIMESTAMP)),
    (66, 'Considering an upgrade once the current contract expires.', DATEADD('DAY', -239, CURRENT_TIMESTAMP)),
    (67, 'Prefers to be contacted by email.', DATEADD('DAY', -178, CURRENT_TIMESTAMP)),
    (67, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -215, CURRENT_TIMESTAMP)),
    (67, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -252, CURRENT_TIMESTAMP)),
    (67, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -289, CURRENT_TIMESTAMP)),
    (67, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -326, CURRENT_TIMESTAMP)),
    (69, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -204, CURRENT_TIMESTAMP)),
    (69, 'Schedule quarterly check-ins going forward.', DATEADD('DAY', -241, CURRENT_TIMESTAMP)),
    (69, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -278, CURRENT_TIMESTAMP)),
    (69, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -315, CURRENT_TIMESTAMP)),
    (70, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -217, CURRENT_TIMESTAMP)),
    (71, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -230, CURRENT_TIMESTAMP)),
    (71, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -267, CURRENT_TIMESTAMP)),
    (71, 'Provided detailed feedback on the new portal.', DATEADD('DAY', -304, CURRENT_TIMESTAMP)),
    (73, 'Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -256, CURRENT_TIMESTAMP)),
    (73, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -293, CURRENT_TIMESTAMP)),
    (74, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -269, CURRENT_TIMESTAMP)),
    (74, 'Requested a copy of the latest product brochure.', DATEADD('DAY', -306, CURRENT_TIMESTAMP)),
    (74, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -343, CURRENT_TIMESTAMP)),
    (74, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -15, CURRENT_TIMESTAMP)),
    (75, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -282, CURRENT_TIMESTAMP)),
    (77, 'Wants to be notified about regional events.', DATEADD('DAY', -308, CURRENT_TIMESTAMP)),
    (77, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -345, CURRENT_TIMESTAMP)),
    (77, 'Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -17, CURRENT_TIMESTAMP)),
    (77, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -54, CURRENT_TIMESTAMP)),
    (77, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -91, CURRENT_TIMESTAMP)),
    (78, 'Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -321, CURRENT_TIMESTAMP)),
    (78, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -358, CURRENT_TIMESTAMP)),
    (79, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -334, CURRENT_TIMESTAMP)),
    (79, 'Flagged as a potential reference customer.', DATEADD('DAY', -6, CURRENT_TIMESTAMP)),
    (79, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -43, CURRENT_TIMESTAMP)),
    (79, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -80, CURRENT_TIMESTAMP)),
    (81, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -360, CURRENT_TIMESTAMP)),
    (81, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -32, CURRENT_TIMESTAMP)),
    (81, 'Very responsive and easy to work with.', DATEADD('DAY', -69, CURRENT_TIMESTAMP)),
    (82, 'Longtime customer with an excellent payment history.', DATEADD('DAY', -8, CURRENT_TIMESTAMP)),
    (82, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -45, CURRENT_TIMESTAMP)),
    (82, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -82, CURRENT_TIMESTAMP)),
    (82, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -119, CURRENT_TIMESTAMP)),
    (82, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -156, CURRENT_TIMESTAMP)),
    (83, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -21, CURRENT_TIMESTAMP)),
    (83, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -58, CURRENT_TIMESTAMP)),
    (85, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -47, CURRENT_TIMESTAMP)),
    (86, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -60, CURRENT_TIMESTAMP)),
    (86, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -97, CURRENT_TIMESTAMP)),
    (86, 'Met at the annual industry conference in March.', DATEADD('DAY', -134, CURRENT_TIMESTAMP)),
    (87, 'Spoke with them about renewal pricing.', DATEADD('DAY', -73, CURRENT_TIMESTAMP)),
    (87, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -110, CURRENT_TIMESTAMP)),
    (87, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -147, CURRENT_TIMESTAMP)),
    (87, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -184, CURRENT_TIMESTAMP)),
    (87, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -221, CURRENT_TIMESTAMP)),
    (89, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -99, CURRENT_TIMESTAMP)),
    (89, 'Considering an upgrade once the current contract expires.', DATEADD('DAY', -136, CURRENT_TIMESTAMP)),
    (89, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -173, CURRENT_TIMESTAMP)),
    (89, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -210, CURRENT_TIMESTAMP)),
    (90, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -112, CURRENT_TIMESTAMP)),
    (91, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -125, CURRENT_TIMESTAMP)),
    (91, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -162, CURRENT_TIMESTAMP)),
    (91, 'Usually unavailable on Friday afternoons.', DATEADD('DAY', -199, CURRENT_TIMESTAMP)),
    (93, 'Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -151, CURRENT_TIMESTAMP)),
    (93, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -188, CURRENT_TIMESTAMP)),
    (94, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -164, CURRENT_TIMESTAMP)),
    (94, 'Provided detailed feedback on the new portal.', DATEADD('DAY', -201, CURRENT_TIMESTAMP)),
    (94, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -238, CURRENT_TIMESTAMP)),
    (94, 'Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -275, CURRENT_TIMESTAMP)),
    (95, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -177, CURRENT_TIMESTAMP)),
    (97, 'Requested a copy of the latest product brochure.', DATEADD('DAY', -203, CURRENT_TIMESTAMP)),
    (97, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -240, CURRENT_TIMESTAMP)),
    (97, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -277, CURRENT_TIMESTAMP)),
    (97, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -314, CURRENT_TIMESTAMP)),
    (97, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -351, CURRENT_TIMESTAMP)),
    (98, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -216, CURRENT_TIMESTAMP)),
    (98, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -253, CURRENT_TIMESTAMP)),
    (99, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -229, CURRENT_TIMESTAMP)),
    (99, 'Recently moved and updated their mailing address.', DATEADD('DAY', -266, CURRENT_TIMESTAMP)),
    (99, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -303, CURRENT_TIMESTAMP)),
    (99, 'Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -340, CURRENT_TIMESTAMP)),
    (101, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -255, CURRENT_TIMESTAMP)),
    (101, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -292, CURRENT_TIMESTAMP)),
    (101, 'Interested in the premium support plan.', DATEADD('DAY', -329, CURRENT_TIMESTAMP)),
    (102, 'Flagged as a potential reference customer.', DATEADD('DAY', -268, CURRENT_TIMESTAMP)),
    (102, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -305, CURRENT_TIMESTAMP)),
    (102, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -342, CURRENT_TIMESTAMP)),
    (102, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -14, CURRENT_TIMESTAMP)),
    (102, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -51, CURRENT_TIMESTAMP)),
    (103, 'Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -281, CURRENT_TIMESTAMP)),
    (103, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -318, CURRENT_TIMESTAMP)),
    (105, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -307, CURRENT_TIMESTAMP)),
    (106, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -320, CURRENT_TIMESTAMP)),
    (106, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -357, CURRENT_TIMESTAMP)),
    (106, 'Left a voicemail regarding the open invoice.', DATEADD('DAY', -29, CURRENT_TIMESTAMP)),
    (107, 'Asked for a follow-up call next quarter.', DATEADD('DAY', -333, CURRENT_TIMESTAMP)),
    (107, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -5, CURRENT_TIMESTAMP)),
    (107, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -42, CURRENT_TIMESTAMP)),
    (107, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -79, CURRENT_TIMESTAMP)),
    (107, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -116, CURRENT_TIMESTAMP)),
    (109, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -359, CURRENT_TIMESTAMP)),
    (109, 'Met at the annual industry conference in March.', DATEADD('DAY', -31, CURRENT_TIMESTAMP)),
    (109, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -68, CURRENT_TIMESTAMP)),
    (109, 'Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -105, CURRENT_TIMESTAMP)),
    (110, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -7, CURRENT_TIMESTAMP)),
    (111, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -20, CURRENT_TIMESTAMP)),
    (111, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -57, CURRENT_TIMESTAMP)),
    (111, 'Prefers to be contacted by email.', DATEADD('DAY', -94, CURRENT_TIMESTAMP)),
    (113, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -46, CURRENT_TIMESTAMP)),
    (113, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -83, CURRENT_TIMESTAMP)),
    (114, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -59, CURRENT_TIMESTAMP)),
    (114, 'Usually unavailable on Friday afternoons.', DATEADD('DAY', -96, CURRENT_TIMESTAMP)),
    (114, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -133, CURRENT_TIMESTAMP)),
    (114, 'Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -170, CURRENT_TIMESTAMP)),
    (115, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -72, CURRENT_TIMESTAMP)),
    (117, 'Provided detailed feedback on the new portal.', DATEADD('DAY', -98, CURRENT_TIMESTAMP)),
    (117, 'Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -135, CURRENT_TIMESTAMP)),
    (117, 'Very responsive and easy to work with. Has two accounts that should eventually be merged.', DATEADD('DAY', -172, CURRENT_TIMESTAMP)),
    (117, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -209, CURRENT_TIMESTAMP)),
    (117, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -246, CURRENT_TIMESTAMP)),
    (118, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -111, CURRENT_TIMESTAMP)),
    (118, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -148, CURRENT_TIMESTAMP)),
    (119, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -124, CURRENT_TIMESTAMP)),
    (119, 'Has two accounts that should eventually be merged.', DATEADD('DAY', -161, CURRENT_TIMESTAMP)),
    (119, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -198, CURRENT_TIMESTAMP)),
    (119, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -235, CURRENT_TIMESTAMP)),
    (121, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -150, CURRENT_TIMESTAMP)),
    (121, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -187, CURRENT_TIMESTAMP)),
    (121, 'Wants to be notified about regional events.', DATEADD('DAY', -224, CURRENT_TIMESTAMP)),
    (122, 'Recently moved and updated their mailing address.', DATEADD('DAY', -163, CURRENT_TIMESTAMP)),
    (122, 'Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -200, CURRENT_TIMESTAMP)),
    (122, 'Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -237, CURRENT_TIMESTAMP)),
    (122, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -274, CURRENT_TIMESTAMP)),
    (122, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history.', DATEADD('DAY', -311, CURRENT_TIMESTAMP)),
    (123, 'Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -176, CURRENT_TIMESTAMP)),
    (123, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -213, CURRENT_TIMESTAMP)),
    (125, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -202, CURRENT_TIMESTAMP)),
    (126, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March.', DATEADD('DAY', -215, CURRENT_TIMESTAMP)),
    (126, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter.', DATEADD('DAY', -252, CURRENT_TIMESTAMP)),
    (126, 'Longtime customer with an excellent payment history.', DATEADD('DAY', -289, CURRENT_TIMESTAMP)),
    (127, 'Very responsive and easy to work with.', DATEADD('DAY', -228, CURRENT_TIMESTAMP)),
    (127, 'Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -265, CURRENT_TIMESTAMP)),
    (127, 'Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice.', DATEADD('DAY', -302, CURRENT_TIMESTAMP)),
    (127, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -339, CURRENT_TIMESTAMP)),
    (127, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -11, CURRENT_TIMESTAMP)),
    (129, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -254, CURRENT_TIMESTAMP)),
    (129, 'Left a voicemail regarding the open invoice.', DATEADD('DAY', -291, CURRENT_TIMESTAMP)),
    (129, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -328, CURRENT_TIMESTAMP)),
    (129, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing.', DATEADD('DAY', -0, CURRENT_TIMESTAMP)),
    (130, 'Considering an upgrade once the current contract expires. Very responsive and easy to work with. Has two accounts that should eventually be merged. Prefers to be contacted by email.', DATEADD('DAY', -267, CURRENT_TIMESTAMP)),
    (131, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons.', DATEADD('DAY', -280, CURRENT_TIMESTAMP)),
    (131, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -317, CURRENT_TIMESTAMP)),
    (131, 'Spoke with them about renewal pricing.', DATEADD('DAY', -354, CURRENT_TIMESTAMP)),
    (133, 'Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires.', DATEADD('DAY', -306, CURRENT_TIMESTAMP)),
    (133, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -343, CURRENT_TIMESTAMP)),
    (134, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -319, CURRENT_TIMESTAMP)),
    (134, 'Prefers to be contacted by email.', DATEADD('DAY', -356, CURRENT_TIMESTAMP)),
    (134, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -28, CURRENT_TIMESTAMP)),
    (134, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward.', DATEADD('DAY', -65, CURRENT_TIMESTAMP)),
    (135, 'Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -332, CURRENT_TIMESTAMP)),
    (137, 'Usually unavailable on Friday afternoons.', DATEADD('DAY', -358, CURRENT_TIMESTAMP)),
    (137, 'Has two accounts that should eventually be merged. Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -30, CURRENT_TIMESTAMP)),
    (137, 'Interested in the premium support plan. Referred by a colleague from the Springfield office.', DATEADD('DAY', -67, CURRENT_TIMESTAMP)),
    (137, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -104, CURRENT_TIMESTAMP)),
    (137, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -141, CURRENT_TIMESTAMP)),
    (138, 'Flagged as a potential reference customer. Provided detailed feedback on the new portal.', DATEADD('DAY', -6, CURRENT_TIMESTAMP)),
    (138, 'Asked for a follow-up call next quarter. Recently moved and updated their mailing address. Usually unavailable on Friday afternoons. Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -43, CURRENT_TIMESTAMP)),
    (139, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -19, CURRENT_TIMESTAMP)),
    (139, 'Referred by a colleague from the Springfield office.', DATEADD('DAY', -56, CURRENT_TIMESTAMP)),
    (139, 'Wants to be notified about regional events. Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -93, CURRENT_TIMESTAMP)),
    (139, 'Longtime customer with an excellent payment history. Requested a copy of the latest product brochure.', DATEADD('DAY', -130, CURRENT_TIMESTAMP)),
    (141, 'Spoke with them about renewal pricing. Flagged as a potential reference customer. Provided detailed feedback on the new portal. Met at the annual industry conference in March. Interested in the premium support plan.', DATEADD('DAY', -45, CURRENT_TIMESTAMP)),
    (141, 'Schedule quarterly check-ins going forward. Asked for a follow-up call next quarter. Recently moved and updated their mailing address.', DATEADD('DAY', -82, CURRENT_TIMESTAMP)),
    (141, 'Requested a copy of the latest product brochure.', DATEADD('DAY', -119, CURRENT_TIMESTAMP)),
    (142, 'Has two accounts that should eventually be merged.', DATEADD('DAY', -58, CURRENT_TIMESTAMP)),
    (142, 'Interested in the premium support plan. Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -95, CURRENT_TIMESTAMP)),
    (142, 'Left a voicemail regarding the open invoice. Wants to be notified about regional events.', DATEADD('DAY', -132, CURRENT_TIMESTAMP)),
    (142, 'Prefers to be contacted by email. Longtime customer with an excellent payment history. Requested a copy of the latest product brochure. Considering an upgrade once the current contract expires. Very responsive and easy to work with.', DATEADD('DAY', -169, CURRENT_TIMESTAMP)),
    (142, 'Referred by a colleague from the Springfield office. Spoke with them about renewal pricing. Flagged as a potential reference customer.', DATEADD('DAY', -206, CURRENT_TIMESTAMP));
