-- Schema for the contact manager database.
CREATE TABLE person (
    person_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(30) NOT NULL,
    last_name      VARCHAR(30) NOT NULL,
    email_address  VARCHAR(30) NOT NULL,
    street_address VARCHAR(60) NOT NULL,
    city           VARCHAR(30) NOT NULL,
    state          CHAR(2)     NOT NULL,
    zip_code       CHAR(5)     NOT NULL
);
